### PR TITLE
fix: use $HOME/.cache for logging

### PR DESCRIPTION
**Pull request by MaximalCats**
Use `$HOME/.cache` if XDG_CACHE_HOME is not set as per the xdg spec, for lazy people like me :p

https://specifications.freedesktop.org/basedir-spec/latest/
> $XDG_CACHE_HOME defines the base directory relative to which user-specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

### CODE REVIEW

**Comment by shvedes** [comment]
Does bash have 2-space tabs standart, or is it just your code editor settings?

**Comment by shvedes** [comment]
Merged anyway. Thank you

**Comment by MaximalCats** [comment]
> Does bash have 2-space tabs standart, or is it just your code editor settings?


Oh oops. Did not notice that. I have neovim set to two spaces. I don't think there is a universal standard for bash scripts though.

**Comment by shvedes** [comment]
Just realized that you are checking the directory existance, not the variable itself. I think it is a better practice to use `[ -z "$XDG_CACHE_HOME" ]` instead.

**Pull request merged**
